---
services:
  s-ui:
    image: zhengxiongzhao/s-ui
    container_name: s-ui
    hostname: "s-ui"
    volumes:
      - "./db:/app/db"
      - "./cert:/app/cert"
    tty: true
    restart: unless-stopped
    ports:
      - "2095:2095"
      - "2096:2096"
      - "63443:63443/udp"
      - "443:443/udp"
    networks:
      - s-ui
    entrypoint: "./entrypoint.sh"

networks:
  s-ui:
    driver: bridge
  